# Generated by Django 6.0.7 on 2026-08-03 20:00

import core.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gadgets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gadget_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='gadgets.gadgettype')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('wifi_ssid', core.fields.EncryptedTextField()),
                ('wifi_password', core.fields.EncryptedTextField()),
                ('receiver_name', models.CharField(max_length=150)),
                ('receiver_phone', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('paid', 'Paid'), ('failed', 'Payment failed'), ('canceled', 'Canceled'), ('assembling', 'Assembling'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='pending_payment', max_length=24)),
                ('tracking_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchases.product')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('zarinpal', 'Zarinpal')], default='zarinpal', max_length=32)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('authority', models.CharField(blank=True, db_index=True, max_length=128)),
                ('ref_id', models.CharField(blank=True, max_length=64)),
                ('card_pan', models.CharField(blank=True, max_length=32)),
                ('fee', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled by user')], default='pending', max_length=16)),
                ('error_code', models.CharField(blank=True, max_length=32)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('gateway_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='purchases.order')),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'success')), fields=('order',), name='one_successful_payment_per_order')],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='purchases_o_user_id_b279ef_idx'),
        ),
    ]
