# Generated by Django 6.0.7 on 2026-08-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_fa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_fa',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
