# Generated by Django 6.0.7 on 2026-08-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_product_persian_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_origin',
            field=models.URLField(blank=True),
        ),
    ]
