# Generated by Django 6.0.7 on 2026-08-03 20:00

import core.fields
import django.db.models.deletion
import django.utils.timezone
import gadgets.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=48)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('direction', models.CharField(choices=[('telemetry', 'Telemetry'), ('command', 'Command')], max_length=16)),
                ('value_type', models.CharField(choices=[('bool', 'Boolean'), ('int', 'Integer'), ('float', 'Float'), ('string', 'String'), ('enum', 'Enum')], max_length=16)),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('max_length', models.PositiveSmallIntegerField(default=64)),
                ('choices', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ('gadget_type', 'direction', 'key'),
            },
        ),
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('secret_key', core.fields.EncryptedTextField(default=gadgets.models.generate_secret_key)),
                ('wifi_ssid', core.fields.EncryptedTextField(blank=True, default='')),
                ('wifi_password', core.fields.EncryptedTextField(blank=True, default='')),
                ('status', models.CharField(choices=[('awaiting_assembly', 'Awaiting assembly'), ('assembled', 'Assembled'), ('shipped', 'Shipped'), ('active', 'Active'), ('disabled', 'Disabled')], default='awaiting_assembly', max_length=24)),
                ('firmware_version', models.CharField(blank=True, max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='GadgetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('telemetry', 'Streams telemetry'), ('action', 'Action / response only'), ('hybrid', 'Both')], max_length=16)),
                ('heartbeat_interval_seconds', models.PositiveIntegerField(default=60)),
                ('offline_after_missed_heartbeats', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TelemetryReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=48)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-recorded_at',),
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('key', models.SlugField(max_length=48)),
                ('value', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent to device'), ('acked', 'Acknowledged'), ('failed', 'Failed'), ('timeout', 'Timed out')], default='pending', max_length=16)),
                ('response', models.JSONField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
