# Generated by Django 6.0.7 on 2026-08-03 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gadgets', '0001_initial'),
        ('purchases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gadget',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gadgets', to='purchases.order'),
        ),
        migrations.AddField(
            model_name='gadget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gadgets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gadget',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gadgets', to='purchases.product'),
        ),
        migrations.AddField(
            model_name='command',
            name='gadget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='gadgets.gadget'),
        ),
        migrations.AddField(
            model_name='gadget',
            name='gadget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gadgets', to='gadgets.gadgettype'),
        ),
        migrations.AddField(
            model_name='capability',
            name='gadget_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='gadgets.gadgettype'),
        ),
        migrations.AddField(
            model_name='telemetryreading',
            name='gadget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='gadgets.gadget'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['gadget', '-created_at'], name='gadgets_com_gadget__08b175_idx'),
        ),
        migrations.AddIndex(
            model_name='gadget',
            index=models.Index(fields=['owner', 'status'], name='gadgets_gad_owner_i_8bc41e_idx'),
        ),
        migrations.AddConstraint(
            model_name='capability',
            constraint=models.UniqueConstraint(fields=('gadget_type', 'direction', 'key'), name='unique_capability_per_type_direction'),
        ),
        migrations.AddIndex(
            model_name='telemetryreading',
            index=models.Index(fields=['gadget', 'key', '-recorded_at'], name='gadgets_tel_gadget__bca65e_idx'),
        ),
    ]
