# Generated by Django 6.0.7 on 2026-08-04 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gadgets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='telemetryreading',
            name='gadgets_tel_gadget__bca65e_idx',
        ),
        migrations.DeleteModel(
            name='TelemetryReading',
        ),
    ]
